AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: callSpeechToTextFFMPEG
Resources:
  ffmpeg:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: ffmpeg
        Description: ffmpeg
        ContentUri: s3://google-speech-to-text-natural-language-function-layers/layer/call_speech_to_text_API/ffmpeg.zip
        CompatibleRuntimes:
          - python3.7
        LicenseInfo:
        RetentionPolicy: Retain

Metadata:
  AWS::ServerlessRepo::Application:
    Name: FfmpegLayerGit
    Description: "hello world"
    Author: kent
    SpdxLicenseId: Python-2.0
    LicenseUrl:
    ReadmeUrl:
    Labels: ['ffmpeg']
    HomePageUrl: https://github.com/dkentoroido/serverlss
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/dkentoroido/serverlss
